### ISSUE TITLE
[bug] Miss dashOffset in 0.5.1

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/three-fatline#8]
Somehow three example lineMaterial.js missing dashoffset in last built...  
So you are also missing dashoffset in 0.5.1, we may need to update

**Comment by vasturiano** [comment]
Thanks for the report @lslzl3000. This bug (introduced in 0.5.1) was recently fixed in the Three repo and I've just applied the fix here too.

I've also added a `dashOffset` control to the example at: https://vasturiano.github.io/three-fatline/example/fat-lines/ to ensure that it's fixed.

Make sure to use `v0.5.2`. 👍
